server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pixdb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    root: INFO
    com.seu.pacote: DEBUG




