version: "3.8"

services:
  postgres:
    container_name: pix-postgres
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: pixdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
