server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: case-chave-pix
    env: dev
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pixdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    root: INFO
    com.seu.pacote: DEBUG




